services:
  - type: web
    name: m-esakafo-web
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t m-esakafo-web .
    startCommand: docker run -p $PORT:80 -e PORT=$PORT m-esakafo-web
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PHP_VERSION
        value: 8.2    # env: docker
    # dockerfilePath: ./Dockerfile
    # buildCommand: docker build -t m-esakafo-web .
    # startCommand: docker run -p $PORT:80 m-esakafo-web


    # env: php
    # buildCommand: composer install
    # startCommand: php -S 0.0.0.0:$PORT -t public/