services:
  - type: web
    name: m-esakafo-web
    env: php
    buildCommand: composer install
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type,Authorization,X-Requested-With,Accept,Origin"
